#include "PluginEditor.h"
#include "PluginProcessor.h"

// BinaryData generated by juce_add_binary_data in CMakeLists.txt.
// Actual symbol names depend on the source filenames (JUCE flattens paths).
// index.html       -> BinaryData::index_html,         BinaryData::index_htmlSize
// js/juce/index.js -> BinaryData::index_js,           BinaryData::index_jsSize
// js/juce/check_native_interop.js
//                  -> BinaryData::check_native_interop_js, BinaryData::check_native_interop_jsSize
#include <BinaryData.h>

//==============================================================================
// Constructor
//
// Initialization order MUST match declaration order in the header:
//   1. Relays
//   2. WebView (built with all relay options)
//   3. Attachments
//   4. addAndMakeVisible + goToURL
//==============================================================================
VocalStripAudioProcessorEditor::VocalStripAudioProcessorEditor (VocalStripAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p),

      // ======================================================================
      // 1 RELAY CONSTRUCTION
      //   Parameter IDs must exactly match APVTS parameter IDs in PluginProcessor.cpp.
      //   The string passed to each relay constructor IS the parameter ID that
      //   JavaScript calls getSliderState("id") / getToggleState("id") / getComboBoxState("id") with.
      // ======================================================================

      // EQ relays
      eqHpEnableRelay      (std::make_unique<juce::WebToggleButtonRelay>("eq_hp_enable")),
      eqLowShelfGainRelay  (std::make_unique<juce::WebSliderRelay>      ("eq_low_shelf_gain")),
      eqMidGainRelay       (std::make_unique<juce::WebSliderRelay>      ("eq_mid_gain")),
      eqMidFreqRelay       (std::make_unique<juce::WebSliderRelay>      ("eq_mid_freq")),
      eqHighShelfGainRelay (std::make_unique<juce::WebSliderRelay>      ("eq_high_shelf_gain")),
      eqBypassRelay        (std::make_unique<juce::WebToggleButtonRelay>("eq_bypass")),

      // Compressor relays
      compModeRelay        (std::make_unique<juce::WebComboBoxRelay>    ("comp_mode")),
      compAmountRelay      (std::make_unique<juce::WebSliderRelay>      ("comp_amount")),
      compThresholdRelay   (std::make_unique<juce::WebSliderRelay>      ("comp_threshold")),
      compRatioRelay       (std::make_unique<juce::WebSliderRelay>      ("comp_ratio")),
      compAttackRelay      (std::make_unique<juce::WebSliderRelay>      ("comp_attack")),
      compReleaseRelay     (std::make_unique<juce::WebSliderRelay>      ("comp_release")),
      compMakeupRelay      (std::make_unique<juce::WebSliderRelay>      ("comp_makeup")),
      compBypassRelay      (std::make_unique<juce::WebToggleButtonRelay>("comp_bypass")),

      // Delay relays
      delayModeRelay       (std::make_unique<juce::WebComboBoxRelay>    ("delay_mode")),
      delayTimeRelay       (std::make_unique<juce::WebSliderRelay>      ("delay_time")),
      delayDivisionRelay   (std::make_unique<juce::WebComboBoxRelay>    ("delay_division")),
      delayFeedbackRelay   (std::make_unique<juce::WebSliderRelay>      ("delay_feedback")),
      delayMixRelay        (std::make_unique<juce::WebSliderRelay>      ("delay_mix")),
      delayReverbSendRelay (std::make_unique<juce::WebSliderRelay>      ("delay_reverb_send")),
      delayBypassRelay     (std::make_unique<juce::WebToggleButtonRelay>("delay_bypass")),

      // Reverb relays
      reverbTypeRelay      (std::make_unique<juce::WebComboBoxRelay>    ("reverb_type")),
      reverbPredelayRelay  (std::make_unique<juce::WebSliderRelay>      ("reverb_predelay")),
      reverbDecayRelay     (std::make_unique<juce::WebSliderRelay>      ("reverb_decay")),
      reverbDampingRelay   (std::make_unique<juce::WebSliderRelay>      ("reverb_damping")),
      reverbMixRelay       (std::make_unique<juce::WebSliderRelay>      ("reverb_mix")),
      reverbBypassRelay    (std::make_unique<juce::WebToggleButtonRelay>("reverb_bypass")),

      // ======================================================================
      // 2 WEBVIEW CONSTRUCTION
      //   All relays must exist before this line.
      //   .withOptionsFrom() registers each relay with the WebView bridge so
      //   the JavaScript side can call getSliderState("id") etc.
      // ======================================================================
      webView (std::make_unique<juce::WebBrowserComponent> (
          juce::WebBrowserComponent::Options{}
              .withNativeIntegrationEnabled()
              .withResourceProvider (
                  [this] (const juce::String& url) { return getResource (url); },
                  juce::WebBrowserComponent::getResourceProviderRoot())
              // EQ relays
              .withOptionsFrom (*eqHpEnableRelay)
              .withOptionsFrom (*eqLowShelfGainRelay)
              .withOptionsFrom (*eqMidGainRelay)
              .withOptionsFrom (*eqMidFreqRelay)
              .withOptionsFrom (*eqHighShelfGainRelay)
              .withOptionsFrom (*eqBypassRelay)
              // Compressor relays
              .withOptionsFrom (*compModeRelay)
              .withOptionsFrom (*compAmountRelay)
              .withOptionsFrom (*compThresholdRelay)
              .withOptionsFrom (*compRatioRelay)
              .withOptionsFrom (*compAttackRelay)
              .withOptionsFrom (*compReleaseRelay)
              .withOptionsFrom (*compMakeupRelay)
              .withOptionsFrom (*compBypassRelay)
              // Delay relays
              .withOptionsFrom (*delayModeRelay)
              .withOptionsFrom (*delayTimeRelay)
              .withOptionsFrom (*delayDivisionRelay)
              .withOptionsFrom (*delayFeedbackRelay)
              .withOptionsFrom (*delayMixRelay)
              .withOptionsFrom (*delayReverbSendRelay)
              .withOptionsFrom (*delayBypassRelay)
              // Reverb relays
              .withOptionsFrom (*reverbTypeRelay)
              .withOptionsFrom (*reverbPredelayRelay)
              .withOptionsFrom (*reverbDecayRelay)
              .withOptionsFrom (*reverbDampingRelay)
              .withOptionsFrom (*reverbMixRelay)
              .withOptionsFrom (*reverbBypassRelay)
      )),

      // ======================================================================
      // 3 ATTACHMENT CONSTRUCTION
      //   Three-parameter constructor required by JUCE 8 (pattern #12).
      //   Third parameter is undoManager (nullptr = no undo support).
      //   Attachments must be constructed AFTER webView.
      // ======================================================================

      // EQ attachments
      eqHpEnableAttachment (std::make_unique<juce::WebToggleButtonParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_hp_enable"),      *eqHpEnableRelay,      nullptr)),
      eqLowShelfGainAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_low_shelf_gain"), *eqLowShelfGainRelay,  nullptr)),
      eqMidGainAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_mid_gain"),       *eqMidGainRelay,       nullptr)),
      eqMidFreqAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_mid_freq"),       *eqMidFreqRelay,       nullptr)),
      eqHighShelfGainAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_high_shelf_gain"),*eqHighShelfGainRelay, nullptr)),
      eqBypassAttachment (std::make_unique<juce::WebToggleButtonParameterAttachment> (
          *audioProcessor.parameters.getParameter ("eq_bypass"),         *eqBypassRelay,        nullptr)),

      // Compressor attachments
      compModeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_mode"),         *compModeRelay,        nullptr)),
      compAmountAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_amount"),       *compAmountRelay,      nullptr)),
      compThresholdAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_threshold"),    *compThresholdRelay,   nullptr)),
      compRatioAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_ratio"),        *compRatioRelay,       nullptr)),
      compAttackAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_attack"),       *compAttackRelay,      nullptr)),
      compReleaseAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_release"),      *compReleaseRelay,     nullptr)),
      compMakeupAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_makeup"),       *compMakeupRelay,      nullptr)),
      compBypassAttachment (std::make_unique<juce::WebToggleButtonParameterAttachment> (
          *audioProcessor.parameters.getParameter ("comp_bypass"),       *compBypassRelay,      nullptr)),

      // Delay attachments
      delayModeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_mode"),        *delayModeRelay,       nullptr)),
      delayTimeAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_time"),        *delayTimeRelay,       nullptr)),
      delayDivisionAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_division"),    *delayDivisionRelay,   nullptr)),
      delayFeedbackAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_feedback"),    *delayFeedbackRelay,   nullptr)),
      delayMixAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_mix"),         *delayMixRelay,        nullptr)),
      delayReverbSendAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_reverb_send"), *delayReverbSendRelay, nullptr)),
      delayBypassAttachment (std::make_unique<juce::WebToggleButtonParameterAttachment> (
          *audioProcessor.parameters.getParameter ("delay_bypass"),      *delayBypassRelay,     nullptr)),

      // Reverb attachments
      reverbTypeAttachment (std::make_unique<juce::WebComboBoxParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_type"),       *reverbTypeRelay,      nullptr)),
      reverbPredelayAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_predelay"),   *reverbPredelayRelay,  nullptr)),
      reverbDecayAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_decay"),      *reverbDecayRelay,     nullptr)),
      reverbDampingAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_damping"),    *reverbDampingRelay,   nullptr)),
      reverbMixAttachment (std::make_unique<juce::WebSliderParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_mix"),        *reverbMixRelay,       nullptr)),
      reverbBypassAttachment (std::make_unique<juce::WebToggleButtonParameterAttachment> (
          *audioProcessor.parameters.getParameter ("reverb_bypass"),     *reverbBypassRelay,    nullptr))
{
    // ========================================================================
    // Post-construction setup
    // ========================================================================

    addAndMakeVisible (*webView);

    // Navigate to the resource provider root (serves index.html)
    webView->goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Fixed canvas size matching v6-ui dimensions: 1120 x 520
    setSize (1120, 520);

    startTimerHz (30);  // 30 Hz GR meter refresh
}

VocalStripAudioProcessorEditor::~VocalStripAudioProcessorEditor()
{
    // Members destroyed automatically in reverse declaration order:
    //   reverbBypassAttachment ... eqHpFreqAttachment  (attachments)
    //   webView                                         (WebView)
    //   reverbBypassRelay ... eqHpFreqRelay             (relays)
}

//==============================================================================
void VocalStripAudioProcessorEditor::paint (juce::Graphics& g)
{
    // Background — WebView covers the entire editor, so nothing to paint.
    g.fillAll (juce::Colour (0xff2a1a08));
}

void VocalStripAudioProcessorEditor::resized()
{
    // WebView fills the entire editor bounds.
    if (webView != nullptr)
        webView->setBounds (getLocalBounds());
}

//==============================================================================
// GR Meter — 30 Hz timer reads gain reduction from processor, drives JS needle
//==============================================================================
void VocalStripAudioProcessorEditor::timerCallback()
{
    if (webView == nullptr)
        return;

    // Read GR value from audio thread atomic (lock-free)
    // Range: 0.0 (no reduction) to -30.0 dB (max reduction)
    const float grDB = audioProcessor.grMeterValue.load();

    // Map dB to needle angle:
    //   0 dB  (no GR)    -> -50 deg (rest position, left)
    //  -20 dB (heavy GR) -> +50 deg (full deflection, right)
    // Linear mapping: angle = -50 + (|grDB| / 20.0f) * 100.0f
    const float absGR = juce::jlimit (0.0f, 20.0f, -grDB);   // 0 to 20
    const float needleAngle = -50.0f + (absGR / 20.0f) * 100.0f;  // -50 to +50

    // Send to JavaScript via evaluateJavascript (message thread safe)
    // JavaScript exposes a global function: updateGRMeter(angle)
    const juce::String js = "if(typeof updateGRMeter==='function')updateGRMeter("
                            + juce::String (needleAngle, 1) + ");";
    webView->evaluateJavascript (js, [] (juce::WebBrowserComponent::EvaluationResult) {});
}

//==============================================================================
// Resource provider — explicit URL mapping (pattern #8 + #13)
//
// BinaryData flattens paths to valid C++ identifiers:
//   Source/ui/public/index.html               -> index_html
//   Source/ui/public/js/juce/index.js         -> index_js
//   Source/ui/public/js/juce/check_native_interop.js -> check_native_interop_js
//
// The browser requests the original paths, so we map explicitly.
//==============================================================================
std::optional<juce::WebBrowserComponent::Resource>
VocalStripAudioProcessorEditor::getResource (const juce::String& url)
{
    auto makeVector = [] (const char* data, int size) -> std::vector<std::byte>
    {
        return std::vector<std::byte> (
            reinterpret_cast<const std::byte*> (data),
            reinterpret_cast<const std::byte*> (data) + size);
    };

    // Serve index.html
    if (url == "/" || url == "/index.html")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_html, BinaryData::index_htmlSize),
            juce::String ("text/html")
        };
    }

    // Serve JUCE WebView integration library (ES6 module — pattern #21)
    if (url == "/js/juce/index.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::index_js, BinaryData::index_jsSize),
            juce::String ("application/javascript")
        };
    }

    // Serve native interop check script (pattern #13 — required for JUCE WebView)
    if (url == "/js/juce/check_native_interop.js")
    {
        return juce::WebBrowserComponent::Resource {
            makeVector (BinaryData::check_native_interop_js, BinaryData::check_native_interop_jsSize),
            juce::String ("application/javascript")
        };
    }

    // 404 — log for debugging
    DBG ("VocalStripEditor::getResource: unhandled URL: " + url);
    return std::nullopt;
}
