#pragma once

#include <juce_audio_processors/juce_audio_processors.h>
#include <juce_gui_extra/juce_gui_extra.h>

// Forward declaration
class VocalStripAudioProcessor;

//==============================================================================
/**
 * VocalStripAudioProcessorEditor
 *
 * WebView-based plugin editor for VocalStrip v6.
 * Generated by ui-finalization-agent from v6-ui.yaml.
 *
 * TEMPLATE FILE — gui-agent adapts this to actual plugin structure during Stage 3.
 *
 * ============================================================
 * CRITICAL MEMBER DECLARATION ORDER
 * ============================================================
 *
 * Members are destroyed in REVERSE order of declaration.
 * WebView attachments call evaluateJavascript() during destruction,
 * so they MUST be destroyed BEFORE the WebView component.
 *
 * Required order (top to bottom in declaration):
 *   1. Relays   (no dependencies)
 *   2. WebView  (depends on relays)
 *   3. Attachments (depend on relays AND webView)
 *
 * Destruction order (reverse of declaration):
 *   1. Attachments destroyed FIRST  -> safe to call webView methods
 *   2. WebView destroyed SECOND     -> attachments are gone
 *   3. Relays destroyed LAST        -> nothing using them
 *
 * Wrong order causes: undefined behaviour in release builds (DAW crashes on reload).
 * ============================================================
 */
class VocalStripAudioProcessorEditor : public juce::AudioProcessorEditor
{
public:
    explicit VocalStripAudioProcessorEditor (VocalStripAudioProcessor& p);
    ~VocalStripAudioProcessorEditor() override;

    void paint (juce::Graphics&) override;
    void resized() override;

private:
    // Resource provider for WebView (explicit URL mapping — see pattern #8)
    std::optional<juce::WebBrowserComponent::Resource>
    getResource (const juce::String& url);

    // Reference to processor
    VocalStripAudioProcessor& audioProcessor;

    // ========================================================================
    // 1 RELAYS FIRST (no dependencies)
    // ========================================================================

    // -- EQ Section --
    std::unique_ptr<juce::WebSliderRelay> eqHpFreqRelay;
    std::unique_ptr<juce::WebSliderRelay> eqLowShelfGainRelay;
    std::unique_ptr<juce::WebSliderRelay> eqLowShelfFreqRelay;
    std::unique_ptr<juce::WebSliderRelay> eqMidGainRelay;
    std::unique_ptr<juce::WebSliderRelay> eqMidFreqRelay;
    std::unique_ptr<juce::WebSliderRelay> eqMidQRelay;
    std::unique_ptr<juce::WebSliderRelay> eqHighShelfGainRelay;
    std::unique_ptr<juce::WebSliderRelay> eqHighShelfFreqRelay;
    std::unique_ptr<juce::WebToggleButtonRelay> eqBypassRelay;

    // -- Compressor Section --
    std::unique_ptr<juce::WebComboBoxRelay> compModeRelay;
    std::unique_ptr<juce::WebSliderRelay> compAmountRelay;
    std::unique_ptr<juce::WebSliderRelay> compThresholdRelay;
    std::unique_ptr<juce::WebSliderRelay> compRatioRelay;
    std::unique_ptr<juce::WebSliderRelay> compAttackRelay;
    std::unique_ptr<juce::WebSliderRelay> compReleaseRelay;
    std::unique_ptr<juce::WebSliderRelay> compMakeupRelay;
    std::unique_ptr<juce::WebToggleButtonRelay> compBypassRelay;

    // -- Delay Section --
    std::unique_ptr<juce::WebComboBoxRelay> delayModeRelay;
    std::unique_ptr<juce::WebSliderRelay> delayTimeRelay;
    std::unique_ptr<juce::WebComboBoxRelay> delayDivisionRelay;
    std::unique_ptr<juce::WebSliderRelay> delayFeedbackRelay;
    std::unique_ptr<juce::WebSliderRelay> delayMixRelay;
    std::unique_ptr<juce::WebSliderRelay> delayReverbSendRelay;
    std::unique_ptr<juce::WebToggleButtonRelay> delayBypassRelay;

    // -- Reverb Section --
    std::unique_ptr<juce::WebComboBoxRelay> reverbTypeRelay;
    std::unique_ptr<juce::WebSliderRelay> reverbPredelayRelay;
    std::unique_ptr<juce::WebSliderRelay> reverbDecayRelay;
    std::unique_ptr<juce::WebSliderRelay> reverbDampingRelay;
    std::unique_ptr<juce::WebSliderRelay> reverbMixRelay;
    std::unique_ptr<juce::WebToggleButtonRelay> reverbBypassRelay;

    // ========================================================================
    // 2 WEBVIEW SECOND (depends on relays; relays must be alive when webView
    //   is constructed so all .withOptionsFrom() calls are valid)
    // ========================================================================
    std::unique_ptr<juce::WebBrowserComponent> webView;

    // ========================================================================
    // 3 ATTACHMENTS LAST (depend on relays AND webView)
    // ========================================================================

    // -- EQ Section --
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqHpFreqAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqLowShelfGainAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqLowShelfFreqAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqMidGainAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqMidFreqAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqMidQAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqHighShelfGainAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      eqHighShelfFreqAttachment;
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> eqBypassAttachment;

    // -- Compressor Section --
    std::unique_ptr<juce::WebComboBoxParameterAttachment>    compModeAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compAmountAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compThresholdAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compRatioAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compAttackAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compReleaseAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      compMakeupAttachment;
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> compBypassAttachment;

    // -- Delay Section --
    std::unique_ptr<juce::WebComboBoxParameterAttachment>    delayModeAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      delayTimeAttachment;
    std::unique_ptr<juce::WebComboBoxParameterAttachment>    delayDivisionAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      delayFeedbackAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      delayMixAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      delayReverbSendAttachment;
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> delayBypassAttachment;

    // -- Reverb Section --
    std::unique_ptr<juce::WebComboBoxParameterAttachment>    reverbTypeAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      reverbPredelayAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      reverbDecayAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      reverbDampingAttachment;
    std::unique_ptr<juce::WebSliderParameterAttachment>      reverbMixAttachment;
    std::unique_ptr<juce::WebToggleButtonParameterAttachment> reverbBypassAttachment;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (VocalStripAudioProcessorEditor)
};
